### ISSUE TITLE
Dalaran Fireworks has unlimited charges/uses

### ISSUE THREAD

**Issue by foufinator** [MondWoW/Bugtracker#10]
**Description**: When u right click Dalaran Fireworks the number of uses/charges dont reduce

**Current behaviour**: Dosent reduce the amount of charges

**Expected behaviour**: When used it should lower the amount of uses/charges by 1

**Steps to reproduce the problem**:

1. get the mailbox present for being lvl 85
2. open it and grab all content
3.  right click the Dalaran Firework and see

**Screenshots**: Screenshots posted to imgur or something similar
https://puu.sh/A2DLg.png (Before)
https://puu.sh/A2DMB.png (After)

**Comment by MondWoW** [comment]
fixed next rev
