### ISSUE TITLE
City Teleport List Missing Alliance Cities

### ISSUE THREAD

**Issue by Jord85** [MondWoW/Bugtracker#11]
**Description**: Only Horde cities and Dalaran are accessible via City Teleporter, even if you're on an alliance character

**Current behaviour**: only shows Horde cities

**Expected behaviour**: show all cities for either faction, or faction specific cities dependant on what character (faction) you're playing on

**Steps to reproduce the problem**:

1. click hearthstone
2. click city teleporter
3. ????
4. Profit

**Comment by MondWoW** [comment]
fixed next rev
