### ISSUE TITLE
Profession vendor in Mission area

### ISSUE THREAD

**Issue by Jord85** [MondWoW/Bugtracker#12]
**Description**: Cost of profession does not equal description amount

**Current behaviour**: Just farmed 5006 MG so I could buy a profession in mission area, bought a profession and checked my MG balance, I've still got 2006MG remaining

**Expected behaviour**: Either change NPC name to reflect on correct MG cost, or change the MG cost to reflect on NPC name.

**Steps to reproduce the problem**:

1. get 5k mg
2. buy profession
3. check remaining mg

**Comment by WiFiHaxr** [comment]
Npc removed as going to add a new one even better
