### ISSUE TITLE
teleporting to ice crown crashes my game 

### ISSUE THREAD

**Issue by ghost** [MondWoW/Bugtracker#13]
**Description**: teleporting to ice crown crashes my game 

**Current behaviour**:  I use the stone to tele to ice crown and the game crashes 

**Expected behaviour**: no game crash 

**Steps to reproduce the problem**:

1. I had to get a dev to get me out of there , cus my game would crash every time I go to log in in ice crown 
2. 
3. 

**Screenshots**: Screenshots posted to imgur or something similar
![untitled](https://user-images.githubusercontent.com/24786223/38767462-e6deb2d8-3fb7-11e8-8bfb-3374681c22b3.png)

**Comment by MondWoW** [comment]
where did you get your client?

**Comment by ghost** [comment]
I downloaded the full client World of Warcraft 4.3.4.15595 - Atlantiss.eu

**Comment by WiFiHaxr** [comment]
You can download our client on the website and it fixes this!
