### ISSUE TITLE
Mats not stacking as they should

### ISSUE THREAD

**Issue by BaconGM** [MondWoW/Bugtracker#15]
****Description**:** Description of the problem.

**Current behaviour**: What happens

**Expected behaviour**: What should happen instead

**Steps to reproduce the problem**:

1. Volatile Air isnt in a stack of 20.
2. They take up all of my bagspace.
3. They should be in stacks of 20.

**Screenshots**: Screenshots posted to imgur or something similar
https://imgur.com/a/rSUPq

**Comment by MondWoW** [comment]
fixed for volatiles, report other items if it happens
