### ISSUE TITLE
Trader (Auction NPC in mission area)

### ISSUE THREAD

**Issue by Jord85** [MondWoW/Bugtracker#16]
**Description**: Not paying out the correct amount for sold items

**Current behaviour**: I placed a stack of parchment for 1 gold buyout price, which should cost 1 MG for someone to buy, and pay me 1MG for the sale. It sold for 1MG to the player, deducted their MG corrently but gave me +150 MG credit in the mail as payment, when sold at a vendor gave me 150 MG instead of the 1MG I should have been paid

**Expected behaviour**: Pay correct amount to the seller

**Steps to reproduce the problem**:

1. place item for auction at trader
2. set price to 1g (I havent tested with other amounts)
3. get someone to buy the item
4. check mailbox to find the money bug (ongoing reported bug) and 150 MG Credits
5. check your current MG, sell the +150 MG credits at a vendor
6. chat log will show '+150 MG!' and will also show when you check your MG balance

![wowscrnshot_041518_104410](https://user-images.githubusercontent.com/38351811/38773851-08c15bd8-409b-11e8-97bb-da1cd0cf4a37.jpg)

![wowscrnshot_041518_104418](https://user-images.githubusercontent.com/38351811/38773864-174418e4-409b-11e8-853a-b14db4fda09a.jpg)

![wowscrnshot_041518_104438](https://user-images.githubusercontent.com/38351811/38773867-1e09f360-409b-11e8-9635-13d5814fa3c5.jpg)

![wowscrnshot_041518_104444](https://user-images.githubusercontent.com/38351811/38773869-23019fda-409b-11e8-8c8a-3a54645355d9.jpg)

![wowscrnshot_041518_104502](https://user-images.githubusercontent.com/38351811/38773880-2b7a17e6-409b-11e8-9a8a-7fe7e545b287.jpg)

![wowscrnshot_041518_104520](https://user-images.githubusercontent.com/38351811/38773881-32404870-409b-11e8-8b69-593670b18ddd.jpg)

**Comment by MondWoW** [comment]
in progress
