### ISSUE TITLE
You don't have any space in your bags.

### ISSUE THREAD

**Issue by xXBentRealityXx** [MondWoW/Bugtracker#17]
**Description**: Upon upgrading my simple chest gear, I don't receive my new item even though it says success. I have 97 spaces in my bags free but still don't receive the item.

**Current behaviour**: Upon upgrading my simple chest gear, I don't receive my new item even though it says success. I have 97 spaces in my bags free but still don't receive the item.

**Expected behaviour**: I should receive the upgraded item.

**Steps to reproduce the problem**:

1. Use the item upgrader.
2. make sure you have the required mats.
3. Notice you don't receive the new item.

**Screenshots**: Screenshots posted to imgur or something similar

**Comment by xXBentRealityXx** [comment]
Update -- Seems to happen on all simple gear, possibly more.

**Comment by MondWoW** [comment]
fixed upgraded Quantity was set to 0
