### ISSUE TITLE
way to much money 

### ISSUE THREAD

**Issue by ghost** [MondWoW/Bugtracker#2]
**Description**:  I got a letter in wow mail and recieved 9 000 000 000 000 000 gold 

**Current behaviour**: I am so far past gold cap its not right 

**Expected behaviour**: not free quattuordecillion worth of gold randomly 

**Steps to reproduce the problem**:

1. I made 4 toons and went to the mail and the package was there but not the money  
2. it only seem to happen once 
3. 

**Screenshots**: Screenshots posted to imgur or something similar
![image](https://user-images.githubusercontent.com/24786223/38710162-4899ce78-3e95-11e8-8d8b-d2b7e45ad512.png)

the server reset and I went back to gold cap  but that is the letter that the cash was in 

I went back to the mail after a server reset and the cash was in my mail again on the same toon 
![image](https://user-images.githubusercontent.com/24786223/38710315-1f8866ce-3e96-11e8-8b5c-1ea139e89be9.png)

**Comment by WiFiHaxr** [comment]
visual bug
