### ISSUE TITLE
Cannot access cataclysm instances.

### ISSUE THREAD

**Issue by TotemWow** [MondWoW/Bugtracker#25]
**Description**: New accounts are unable to enter cataclysm instances

**Current behaviour**: When attempting to teleport with might and magic, or through quests the error "This area is not yet available" happens. This applies to all cataclysm intances, blackrock caverns, crysis, shivering isles. (and maybe more). Note this happens on all difficulties too.

**Expected behaviour**: The character should be teleported to the instance.

**Steps to reproduce the problem**:

1. Download wow from website
2. Create a new character on a new account
3. Accept the Your First Destiny Quest - you won't be teleported
4. Try and teleport to blackrock caverns with might and magic - you won't be teleported.
5. Run to instance start - you cannot enter

**Screenshots**: 
![quest](https://user-images.githubusercontent.com/38428751/38809589-eab1feae-417b-11e8-8440-c1af2e4c79ab.png)

![might_and_magic](https://user-images.githubusercontent.com/38428751/38809604-f70f2dfc-417b-11e8-93a2-64f140f25def.png)

**Comment by Artamedes** [comment]
I believe the website isn't giving expansion 3(cataclysm)
