### ISSUE TITLE
Shaman cannot wield swords

### ISSUE THREAD

**Issue by TotemWow** [MondWoW/Bugtracker#26]
**Description**: Shaman are by default not able to wield swords, however the thunderfury is a recommended item for shaman. 

**Current behaviour**: Shaman cannot learn to wield swords.

**Expected behaviour**: Shaman start with sword proficiency 

**Steps to reproduce the problem**:

1. Start a new shaman character
2. Complete the first quests
3. Complete the legendary item quest, and thunderfury is recommended for shaman.

**Screenshots**: 
![image](https://user-images.githubusercontent.com/38428751/38809703-5b57816a-417c-11e8-9740-6fda97b6a894.png)

**Comment by Jord85** [comment]
Shaman have never been able to use swords by default. Axes, Daggers, Fists, Maces and Staves only since Vanilla. The flavor-text is wrong, unless you can learn all proficiencies through VP/DP later on.

**Comment by TotemWow** [comment]
On old Mond shaman were always able to use swords - I imagine it would be the same here.

**Comment by WiFiHaxr** [comment]
fixed
