### ISSUE TITLE
npc will not accept its own finished quest 

### ISSUE THREAD

**Issue by ghost** [MondWoW/Bugtracker#27]
**Description**: blackrock caverns , Finkle Einhorn gives you a quest but will not let you turn it in 

**Current behavior**: cant turn in a quest that the npc gives you 

**Expected behavior**: What should happen instead

**Steps to reproduce the problem**:

1. finish blackrock quest 
2. there will be one that you cant turn in the other 3 work fine 
3.  

**Screenshots**: Screenshots posted to imgur or something similar
![wowscrnshot_041618_143747](https://user-images.githubusercontent.com/24786223/38825851-56944f66-4184-11e8-82c7-c0b3ac2e317a.jpg)
he wont let you finish that mission , so you don't get to chose a trinket

**Comment by Artamedes** [comment]
delete cache, it's click to complete

**Comment by ghost** [comment]
![wowscrnshot_041818_221237](https://user-images.githubusercontent.com/24786223/38965915-cd0625a2-4355-11e8-8f90-2bc592151395.jpg)
 he does not acknowledge its his quest . its not click to accept , it has to be turned in

**Comment by ghost** [comment]
![wowscrnshot_042918_154742](https://user-images.githubusercontent.com/24786223/39409896-ce6ded4a-4bc4-11e8-8afb-757ab2246097.jpg)
 many people are having the same issue with this quest ,
