### ISSUE TITLE
Queen of night Vip Wep Damage

### ISSUE THREAD

**Issue by TotemWow** [MondWoW/Bugtracker#28]
**Description**: Weapon damage on dream vip weapons is 3995 not what it says.

**Current behaviour**: Weapon damage on dream vip weapons is 3995 not what it says.

**Expected behaviour**: Weapon damage should be a lot higher

**Steps to reproduce the problem**:

1. In shop all melee weapons is low damage.
2. 
3. 

**Screenshots**: 
![image](https://user-images.githubusercontent.com/38428751/38829602-820de364-41b1-11e8-9042-8065d51fb93d.png)
![image](https://user-images.githubusercontent.com/38428751/38829606-868bf2dc-41b1-11e8-9f8c-09aa2dacd965.png)
![image](https://user-images.githubusercontent.com/38428751/38829624-971b00b6-41b1-11e8-99c9-c0da941ea9c4.png)

**Comment by Artamedes** [comment]
not an issue, weapon damage is in the NAME, in cataclysm wep damage is based off speed, itemlevel, quality and is much harder to do fixed values. hence why the 250000 - 250000

if the weapons have lower than normal damage in ur char window report that

**Comment by TotemWow** [comment]
@Artamedes 
![image](https://user-images.githubusercontent.com/38428751/38856272-ea2f590c-421d-11e8-9cf5-2e95456500f8.png)
660000-660001 and 330000-3300001
My damage ends up being 65146.8 dps and 32573.4 dps. 

Combat Log: 
![image](https://user-images.githubusercontent.com/38428751/38856361-2286e9be-421e-11e8-9f5e-f15bd5845a7b.png)

The item level of dream weps is significantly higher than queen (and dps on the weapon is too, although you've said to discount that). I don't have dream weapons to compare against on a dummy but...

**Comment by Jord85** [comment]
you posted this after the topic was closed, open a new bug report with the above info and link this thread as a reference

**Comment by Artamedes** [comment]
yes DB has wrong values in minDMG and maxDMG , it will be fixed next crash/restart
