### ISSUE TITLE
Deathknight Runeforging

### ISSUE THREAD

**Issue by Jord85** [MondWoW/Bugtracker#29]
**Description**: Can't use Runeforging as a Deathknight

**Current behaviour**: Runeforging skill doesn't appear in spell book anywhere, even after visiting class trainer and learning everything. 

**Expected behaviour**: Runeforging should be available to be used upon character creation by default

**Steps to reproduce the problem**:

1. Make DK
2. Try Runeforge
3. Cry
4. Reroll to warrior instead

**Comment by ghost** [comment]
I have received a ticket as well from another player who is having the same issue , just thought id mention it instead of making a new bug report 
![wowscrnshot_041918_103949](https://user-images.githubusercontent.com/24786223/38995179-c2419be2-43be-11e8-8945-c260d079ee60.jpg)

**Comment by WiFiHaxr** [comment]
disabled to overpowered
