### ISSUE TITLE
Quest for Azzinoth, the Illidan's Fury

### ISSUE THREAD

**Issue by TotemWow** [MondWoW/Bugtracker#30]
**Description**: Once you max both warglaves, there is no quest for Azzinoth, the Illidan's Fury.

**Current behaviour**: Once you max both warglaves, there is no quest for Azzinoth, the Illidan's Fury.

**Expected behaviour**: A quest allowing you to make +11 Azzinoth, the Illidan's Fury.

**Steps to reproduce the problem**:

1. Get both Warglaves to +10
2. No Quest
3. 

**Screenshots**: 
![image](https://user-images.githubusercontent.com/38428751/38857409-1b9d5946-4221-11e8-9a62-2704f8ee43c4.png)
![image](https://user-images.githubusercontent.com/38428751/38857412-215097d6-4221-11e8-9cdb-a519a19a6412.png)
![image](https://user-images.githubusercontent.com/38428751/38857421-25f267b0-4221-11e8-965f-8b5e14a6d7c1.png)

**Comment by Jord85** [comment]
I cant even get the warglaives

**Comment by TotemWow** [comment]
@Jord85 you don't actually need the warglaives the quest only required the starter Alcaz's Tulwar, and succinctness negation.

**Comment by Jord85** [comment]
yeah i cant get the tulwar

**Comment by TotemWow** [comment]
They're sold at the starting island (not MA)

**Comment by WiFiHaxr** [comment]
fixed
