### ISSUE TITLE
Frostmourne Model Effect

### ISSUE THREAD

**Issue by TotemWow** [MondWoW/Bugtracker#33]
**Description**: The frostmourne aspect of ice effect turns you into a huge model.

**Current behaviour**: Giant Model filling up screen

**Expected behaviour**: The model should be a small lich king? 

**Steps to reproduce the problem**:

1. Get frostmourne +15, equip it
2. Turns you into giant model
3. 

**Screenshots**: 
![image](https://user-images.githubusercontent.com/38428751/39059423-5682e85e-44b6-11e8-970e-d24b5787f73a.png)

**Comment by WiFiHaxr** [comment]
fixed
