### ISSUE TITLE
Thunderfury Blessed Blade of the Windseeker

### ISSUE THREAD

**Issue by TotemWow** [MondWoW/Bugtracker#38]
**Description**: Thunderfury Blessed Blade of the Windseeker is not available to be upgraded

**Current behaviour**: The item is not able to be upgraded 

**Expected behaviour**: The item should be able to be upgraded and bring up the upgrade window

**Steps to reproduce the problem**:

1. Get Thunderfury either from starting quest, or questline in silithus
2.  Try to upgrade with upgrade translation
3.  Item is not upgradable

**Notes**: This happens to both versions of Thunderfury Blessed Blade of the Windseeker, both from the questline and from the starter quest.

**Screenshots**: 
![image](https://user-images.githubusercontent.com/38428751/39247409-3e8a6216-4891-11e8-8dd8-99176fec1309.png)
![image](https://user-images.githubusercontent.com/38428751/39247416-454e623c-4891-11e8-979b-d4a015c1ca03.png)

**Comment by WiFiHaxr** [comment]
fixed
