### ISSUE TITLE
Selling MG

### ISSUE THREAD

**Issue by Nickpostsalotfuckingfag** [MondWoW/Bugtracker#40]
MG does not re sell for its correct value. 

Sell rate capped at 12g to stop gold farming but now I can only sell my 120k mg stack for 12 mg.

It should sell the MG correctly but remove the gold return option 

**Steps to reproduce the problem**:

1. Transfer MG to bag
2. sell mg to npc
3.  profit

**Screenshots**: Screenshots posted to imgur or something similar

**Comment by WiFiHaxr** [comment]
Mg can only be sold to Mg Economy
