### ISSUE TITLE
Rogue spell

### ISSUE THREAD

**Issue by Opopiipo** [MondWoW/Bugtracker#44]
**Description**: Description of the problem.
It only hits 2 targets which originally should be unlimited targets
**Current behaviour**: What happens
Now its just 2 targets
**Expected behaviour**: What should happen instead
Unlimited targets
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Screenshots**: Screenshots posted to imgur or something similar

**Comment by WiFiHaxr** [comment]
fixed
