### ISSUE TITLE
Professions

### ISSUE THREAD

**Issue by Opopiipo** [MondWoW/Bugtracker#45]
**Description**: Description of the problem.
Inscription and Enchanting
**Current behaviour**: What happens
-Inscription: when you buy Virtuoso Inking Set which is a vital item for creating Glyphs it bugs the whole thing, wow Crash with an error and literally wont make u log in again cuz you get that error once you do
-Enchanting:when you spend 5k MG to learn all of it its not 525 its 425
**Expected behaviour**: What should happen instead
i think its Obvious now :)
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Screenshots**: Screenshots posted to imgur or something similar
![untitled 1](https://user-images.githubusercontent.com/38861191/39558875-7cbfaf52-4ea7-11e8-97c0-db5de6ebbc36.png)
![untitled 2](https://user-images.githubusercontent.com/38861191/39558876-7cf64e72-4ea7-11e8-8d3b-0b1f19b523ed.png)
![wowscrnshot_050318_075705](https://user-images.githubusercontent.com/38861191/39558903-a5e2538a-4ea7-11e8-811c-caa7a30723f6.jpg)

**Comment by WiFiHaxr** [comment]
dont care, its not getting fixed. Removed NPC and is no long aval
