### ISSUE TITLE
kills for quest dont count twards the quest 

### ISSUE THREAD

**Issue by ghost** [MondWoW/Bugtracker#46]
![wowscrnshot_050618_014225](https://user-images.githubusercontent.com/24786223/39669910-188098ec-50cf-11e8-868e-f4cc76bdccad.jpg)

the mob is killed and the kill credit does not show

**Comment by ghost** [comment]
![wowscrnshot_050618_015158](https://user-images.githubusercontent.com/24786223/39670000-392a850c-50d0-11e8-9869-a4b6b324f99d.jpg)
 all the way to the end , and no credit from any kill ,

**Comment by Jord85** [comment]
just tried this on a new character and had the same issue
