### ISSUE TITLE
blackrock cavern mobs dont drop MG 

### ISSUE THREAD

**Issue by ghost** [MondWoW/Bugtracker#47]
![wowscrnshot_050618_131306](https://user-images.githubusercontent.com/24786223/39675325-e38ffbee-512f-11e8-860b-bb1b57b575f5.jpg)
![wowscrnshot_050618_131445](https://user-images.githubusercontent.com/24786223/39675327-ea7a1052-512f-11e8-9ce7-46da886b8c07.jpg)
there is no conversation 10 , and between the 2 screenshots ,mobs were killed 
blackrock dont drop MG

**Comment by Jord85** [comment]
there is a MG farm area, 15 MG per kill. Mobs have 5600k hp if i remember correctly

**Comment by WiFiHaxr** [comment]
already fixed
