### ISSUE TITLE
Long ass wow error

### ISSUE THREAD

**Issue by Opopiipo** [MondWoW/Bugtracker#48]
**Description**: Description of the problem.
some cities give some wow error that wont even let you log in again 
**Current behaviour**: What happens
when you wanna log in you get that shit oh sorry not shit you get that wow error again. And then you gotta ask some of staff team to unstuck you :|
**Expected behaviour**: What should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Screenshots**: Screenshots posted to imgur or something similar

**Comment by xXBentRealityXx** [comment]
This error goes away when you download our client, other clients don't work.
