### ISSUE TITLE
death coil spell moves training dummies 

### ISSUE THREAD

**Issue by ghost** [MondWoW/Bugtracker#5]
**Description**:death coil spell moves training dummies 

**Current behaviour**: death coil spell moves training dummies 

**Expected behaviour**: im not sure but I dont think it should , I could move them all 

**Steps to reproduce the problem**:

1. be a warlock 
2. cast death coil on a training dummy 
3. watch em go 

**Screenshots**: Screenshots posted to imgur or something similar
![image](https://user-images.githubusercontent.com/24786223/38737089-766c4406-3f04-11e8-83c5-685c4ea8120d.png)

**Comment by MondWoW** [comment]
fixed next rev
