### ISSUE TITLE
Enchanting

### ISSUE THREAD

**Issue by Opopiipo** [MondWoW/Bugtracker#51]
**Description**: Description of the problem.
Hurricane Does not proc after the first time it happens or it barely happens or not at all.
**Current behaviour**: What happens
Doesnt proc after first time even with low haste like 0.04
**Expected behaviour**: What should happen instead
Gotta proc more often and ofc it gotta proc 100% after the first time with low haste like 0.04. But it doesnt.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Screenshots**: Screenshots posted to imgur or something similar

**Comment by WiFiHaxr** [comment]
this has been taken out of the game
