### ISSUE TITLE
profession trainer

### ISSUE THREAD

**Issue by Jord85** [MondWoW/Bugtracker#57]
**Description**: Removes 3000MG when trying to purchase more than 2 professions, but does not grant you a 3rd profession.

**Current behaviour**: removes 3000mg when trying to purchase another profession after having 2

**Expected behaviour**: either not remove the mg, or allow players to have more than 2 primary professions

![wowscrnshot_051518_134831](https://user-images.githubusercontent.com/38351811/40035862-3df1fe70-5847-11e8-9b8e-ff7d2f8700b0.jpg)

**Comment by WiFiHaxr** [comment]
fixed
