### ISSUE TITLE
Incorrect Item Name

### ISSUE THREAD

**Issue by Jord85** [MondWoW/Bugtracker#6]
**Description**: Custom item name for pants

**Current behaviour**: Showing incorrect name, 'Suspiciously Crusty Socks' It's the name of my boots showing

**Expected behaviour**: Should show correct name - 'Yoga Pants'

Was told to post here, its not really a game bug and im happy to wait as it's not gamebreaking/unbalanced

**Comment by WiFiHaxr** [comment]
Fixed
