### ISSUE TITLE
essence farm mobs have 1 hp 

### ISSUE THREAD

**Issue by ghost** [MondWoW/Bugtracker#64]
the essence farm right now does not drop the proper drops , and the mobs have 1 hp 
![wowscrnshot_051718_200440](https://user-images.githubusercontent.com/24786223/40208038-f2cbac98-5a0d-11e8-9232-9ef1a33ff4ba.jpg)

**Comment by ghost** [comment]
so you are not able to upgrade your weapons as well becouse the drops are not provided 
![wowscrnshot_051718_234324](https://user-images.githubusercontent.com/24786223/40213519-42bd3938-5a2c-11e8-87d1-4555bfb2540f.jpg)

**Comment by WiFiHaxr** [comment]
All drops have been added and are now working
