### ISSUE TITLE
you are not rewarded with a stone to be able to get out of the starter mall 

### ISSUE THREAD

**Issue by ghost** [MondWoW/Bugtracker#65]
![wowscrnshot_051718_235411](https://user-images.githubusercontent.com/24786223/40213865-1af9f830-5a2e-11e8-9f51-b7ea15e307ab.jpg)
 I did all the quest an the line breaks by not providing new players with the might and magic stone to be able to teleport to talk to trade

**Comment by WiFiHaxr** [comment]
This has been Fixed
