### ISSUE TITLE
Profession item not working as intended

### ISSUE THREAD

**Issue by Jord85** [MondWoW/Bugtracker#66]
**Description**: Item requires a prerequisite that I have but will not allow me to equip it

**Current behaviour**: Trying to equip my Gnomish Gravity Well trinket, I farmed the materials and made it with max Engineering skill, tried to equip it and get an error stating I need Gnomish Engineering. I used gnomish engineering to make the item.

**Expected behaviour**: Should allow me to equip it

**Screenshots**: 
Error showing I need Gnomish engineering, Engineering crafting book open to the item i just crafted, chat window shows me just craft it, bottom right shows me mousing over the skill I have yet require to use.

![wowscrnshot_051918_194632](https://user-images.githubusercontent.com/38351811/40267295-ebb8ce2c-5b9d-11e8-8741-8d51a36de1cb.jpg)

**Comment by WiFiHaxr** [comment]
This means the item has been blocked by my system for a reason.
