### ISSUE TITLE
teleporter not working properly 

### ISSUE THREAD

**Issue by ghost** [MondWoW/Bugtracker#7]
**Description**: teleporter not working properly 

**Current behaviour**: I took the first quest to blackrock caverns , left the instance , now I cant teleport there with the stone 

**Expected behaviour**:teleport stone should teleport me to blackrock cavern but just closes the hearthstone instead 

**Steps to reproduce the problem**:

1. both my gm and my alt account have the same issue 
2. 
3. 

**Screenshots**: Screenshots posted to imgur or something similar
![image](https://user-images.githubusercontent.com/24786223/38744209-879c77ba-3f17-11e8-85e3-4307f391d547.png)

**Comment by MondWoW** [comment]
in progress

**Comment by MondWoW** [comment]
fixed next rev
