### ISSUE TITLE
In Alcaz Island the quest giver is attackble

### ISSUE THREAD

**Issue by cocksucker69** [MondWoW/Bugtracker#81]
**Description**: Can't take the quest since they are attackable.

**Current behaviour**: They start too attack you

**Expected behaviour**: be able too take the quest from them so new players can play.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Screenshots**: Screenshots posted to imgur or something similar

![](https://i.gyazo.com/thumb/1200/7261e1e8b603e25e48445218f97a0098-jpg.jpg)

**Comment by jawkneeb123** [comment]
![wowscrnshot_060718_183234](https://user-images.githubusercontent.com/24786223/41127465-687ee26a-6a81-11e8-9a38-297811245594.jpg)
 fixed
