### ISSUE TITLE
clicking the complete quest does not close the window 

### ISSUE THREAD

**Issue by ghost** [MondWoW/Bugtracker#9]
**Description**:clicking the complete quest does not close the window 

**Current behaviour**:you have to click the x , on the quest window for certain quest 

**Expected behaviour**: once you click complete quest it should close the window 

**Steps to reproduce the problem**:
1.
2. 
3. 

**Screenshots**: Screenshots posted to imgur or something similar
![wowscrnshot_041318_155235](https://user-images.githubusercontent.com/24786223/38752843-ea31ff06-3f32-11e8-984a-7cdd6bbc8928.jpg)

**Comment by MondWoW** [comment]
fixed next rev
