### ISSUE TITLE
error #134 after choosing Realm!

### ISSUE THREAD

**Issue by wartronk** [MondWoW/Bugtracker#99]
**Description**: When i select the realm "Mystery Fun Realm" it throws me an error #134

**Current behaviour**: When i select the realm "Mystery Fun Realm" it throws me an error #134 the game closes

**Expected behaviour**: Login in the realm

**Steps to reproduce the problem**:

1. open launcher
2. select the realm
3. error #134

**Screenshots**: 
==============================================================================
World of WarCraft: Retail Build (build 20000)

Exe:      C:\Users\barte\Desktop\World of Warcraft FULL - Cataclysm 4.3.4 (15595)\Mond.exe
Time:     Jul  2, 2018  4:42:24.467 AM
User:     barte
Computer: ---------
------------------------------------------------------------------------------

This application has encountered a critical error:

ERROR #134 (0x85100086) Fatal condition!

Program:	C:\Users\barte\Desktop\World of Warcraft FULL - Cataclysm 4.3.4 (15595)\Mond.exe
ProcessID:	8724

Unknown error code : 2232418453

**Comment by wartronk** [comment]
why you close you dont answer

**Comment by WiFiHaxr** [comment]
Cause it's fixed if you download the Files on the website!
